//Importando datos
import fs, { Stats } from "fs";
let data = JSON.parse(fs.readFileSync("factbook_limpio.json","utf-8"));

//Lista de países
let listapaises = [
    "world",
    "afghanistan",
    "akrotiri_and_dhekelia",
    "albania",
    "algeria",
    "american_samoa",
    "andorra",
    "angola",
    "anguilla",
    "antarctica",
    "antigua_and_barbuda",
    "argentina",
    "armenia",
    "aruba",
    "ashmore_and_cartier_islands",
    "australia",
    "austria",
    "azerbaijan",
    "the_bahamas",
    "bahrain",
    "bangladesh",
    "barbados",
    "belarus",
    "belgium",
    "belize",
    "benin",
    "bermuda",
    "bhutan",
    "bolivia",
    "bosnia_and_herzegovina",
    "botswana",
    "bouvet_island",
    "brazil",
    "british_indian_ocean_territory",
    "british_virgin_islands",
    "brunei",
    "bulgaria",
    "burkina_faso",
    "burma",
    "burundi",
    "cabo_verde",
    "cambodia",
    "cameroon",
    "canada",
    "cayman_islands",
    "central_african_republic",
    "chad",
    "chile",
    "china",
    "christmas_island",
    "clipperton_island",
    "cocos_keeling_islands",
    "colombia",
    "comoros",
    "congo_democratic_republic_of_the",
    "congo_republic_of_the",
    "cook_islands",
    "coral_sea_islands",
    "costa_rica",
    "cote_divoire",
    "croatia",
    "cuba",
    "curacao",
    "cyprus",
    "czechia",
    "denmark",
    "djibouti",
    "dominica",
    "dominican_republic",
    "ecuador",
    "egypt",
    "el_salvador",
    "equatorial_guinea",
    "eritrea",
    "estonia",
    "eswatini",
    "ethiopia",
    "european_union",
    "falkland_islands_islas_malvinas",
    "faroe_islands",
    "fiji",
    "finland",
    "france",
    "french_polynesia",
    "french_southern_and_antarctic_lands",
    "gabon",
    "gambia",
    "gaza_strip",
    "georgia",
    "germany",
    "ghana",
    "gibraltar",
    "greece",
    "greenland",
    "grenada",
    "guam",
    "guatemala",
    "guernsey",
    "guinea",
    "guinea_bissau",
    "guyana",
    "haiti",
    "heard_island_and_mcdonald_islands",
    "holy_see_vatican_city",
    "honduras",
    "hong_kong",
    "hungary",
    "iceland",
    "india",
    "indonesia",
    "iran",
    "iraq",
    "ireland",
    "isle_of_man",
    "israel",
    "italy",
    "jamaica",
    "jan_mayen",
    "japan",
    "jersey",
    "jordan",
    "kazakhstan",
    "kenya",
    "kiribati",
    "korea_north",
    "korea_south",
    "kosovo",
    "kuwait",
    "kyrgyzstan",
    "laos",
    "latvia",
    "lebanon",
    "lesotho",
    "liberia",
    "libya",
    "liechtenstein",
    "lithuania",
    "luxembourg",
    "macau",
    "madagascar",
    "malawi",
    "malaysia",
    "maldives",
    "mali",
    "malta",
    "marshall_islands",
    "mauritania",
    "mauritius",
    "mexico",
    "micronesia_federated_states_of",
    "moldova",
    "monaco",
    "mongolia",
    "montenegro",
    "montserrat",
    "morocco",
    "mozambique",
    "namibia",
    "nauru",
    "navassa_island",
    "nepal",
    "netherlands",
    "new_caledonia",
    "new_zealand",
    "nicaragua",
    "niger",
    "nigeria",
    "niue",
    "norfolk_island",
    "north_macedonia",
    "northern_mariana_islands",
    "norway",
    "oman",
    "pakistan",
    "palau",
    "panama",
    "papua_new_guinea",
    "paracel_islands",
    "paraguay",
    "peru",
    "philippines",
    "pitcairn_islands",
    "poland",
    "portugal",
    "puerto_rico",
    "qatar",
    "romania",
    "russia",
    "rwanda",
    "saint_barthelemy",
    "saint_helena_ascension_and_tristan_da_cunha",
    "saint_kitts_and_nevis",
    "saint_lucia",
    "saint_martin",
    "saint_pierre_and_miquelon",
    "saint_vincent_and_the_grenadines",
    "samoa",
    "san_marino",
    "sao_tome_and_principe",
    "saudi_arabia",
    "senegal",
    "serbia",
    "seychelles",
    "sierra_leone",
    "singapore",
    "sint_maarten",
    "slovakia",
    "slovenia",
    "solomon_islands",
    "somalia",
    "south_africa",
    "south_georgia_and_south_sandwich_islands",
    "south_sudan",
    "spain",
    "spratly_islands",
    "sri_lanka",
    "sudan",
    "suriname",
    "svalbard",
    "sweden",
    "switzerland",
    "syria",
    "taiwan",
    "tajikistan",
    "tanzania",
    "thailand",
    "timor_leste",
    "togo",
    "tokelau",
    "tonga",
    "trinidad_and_tobago",
    "tunisia",
    "turkey_turkiye",
    "turkmenistan",
    "turks_and_caicos_islands",
    "tuvalu",
    "uganda",
    "ukraine",
    "united_arab_emirates",
    "united_kingdom",
    "united_states",
    "united_states_pacific_island_wildlife_refuges",
    "uruguay",
    "uzbekistan",
    "vanuatu",
    "venezuela",
    "vietnam",
    "virgin_islands",
    "wake_island",
    "wallis_and_futuna",
    "west_bank",
    "yemen",
    "zambia",
    "zimbabwe"
  ];
  
      
  


//Declarando funciones útiles

function contienedato(pais,dato) {
    if (traer(pais,dato) != undefined){
        return true;
    }
    else {
        return false;
    }
}

function traer(pais,dato) {
dato = dato.split(".");
return data[pais]?.[dato[0]]?.[dato[1]]?.[dato[2]];
}

function comparar(pais1,pais2,dato){
    if (traer(pais1,dato) > traer(pais2,dato)){
        return true;
    }
    else {
        return false;
    }
}

function paisrandom() {
 let numero = Math.round(Math.random() * listapaises.length);
 return listapaises[numero];
} //Por ahora la función solo da un entero al azar según cantidad de países.


function paisdiario() {

}

function datorandom(pais){

}
//console.log(comparar("uruguay","people.population.total"));
let i = 0;
while (i < 100){let paisrando = paisrandom();
console.log(traer(paisrando,"people.population.total"));
console.log(paisrando);
i++;}
